language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py27-django1.8-drf3.3
    - TOX_ENV=py34-django1.9-drf3.3

matrix:
  fast_finish: true

install:
  - pip install tox python-coveralls

script:
    - tox -e $TOX_ENV

after_success:
  - coveralls
